#controlplane $ k get sa -n ns-secure secret-manager -oyaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-07-16T06:55:02Z"
  name: secret-manager
  namespace: ns-secure
  resourceVersion: "2223"
  uid: fb5e1522-00d6-4206-8c4f-507b5dab4208
secrets:
- name: secret-manager-token-77k7l
#controlplane $ cat pod.yaml 
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-manager
  name: secret-manager
  namespace: ns-secure
spec:
  containers:
  - image: httpd:alpine
    name: secret-manager
    env:
      - name: SEC_A1
        valueFrom:
          secretKeyRef:
            name: sec-a1
            key: passwd 
    volumeMounts: 
    - name: sec-a2
      mountPath: /etc/sec-a2
  volumes:
  - name: sec-a2
    secret:
      secretName: sec-a2
  serviceAccountName: secret-manager
