#apiVersion: v1
#data:
#  hosts: MTI3LjAuMC4xCWxvY2FsaG9zdAoxMjcuMC4xLjEJaG9zdDAxCgojIFRoZSBmb2xsb3dpbmcgbGluZXMgYXJlIGRlc2lyYWJsZSBmb3IgSVB2NiBjYXBhYmxlIGhvc3RzCjo6MSAgICAgbG9jYWxob3N0IGlwNi1sb2NhbGhvc3QgaXA2LWxvb3BiYWNrCmZmMDI6OjEgaXA2LWFsbG5vZGVzCmZmMDI6OjIgaXA2LWFsbHJvdXRlcnMKMTI3LjAuMC4xIGhvc3QwMQoxMjcuMC4wLjEgaG9zdDAxCjEyNy4wLjAuMSBob3N0MDEKMTI3LjAuMC4xIGNvbnRyb2xwbGFuZQoxNzIuMTcuMC4zNSBub2RlMDEKMTcyLjE3LjAuMjMgY29udHJvbHBsYW5lCg==
#kind: Secret
#metadata:
#  name: diver
#k create secret generic holy --from-literal creditcard=1111222233334444
#k create secret generic --from-file=/opt/ks/secret-diver.yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - image: nginx
    name: pod1
    env:
      - name: HOLY
        valueFrom:
          secretKeyRef:
            name: holy
            key: creditcard
    volumeMounts:
    - name: diver
      mountPath: /etc/diver/hosts
  volumes:
  - name: diver
    secret:
      secretName: diver

-
#controlplane $ k -n one get secrets s1 -ojsonpath={}
#{"apiVersion":"v1","data":{"data":"c2VjcmV0"},"kind":"Secret","metadata":{"creationTimestamp":"2022-07-16T06:35:57Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:data":{}},"f:type":{}},"manager":"kubectl-create","operation":"Update","time":"2022-07-16T06:35:57Z"}],"name":"s1","namespace":"one","resourceVersion":"1641","uid":"ee2d3461-f097-4815-bbb8-af2b8c48b484"},"type":"Opaque"}controlplane $ k -n one get secrets s1 -ojsonpath={.data.data}
#c2VjcmV0controlplane $ k -n one get secrets s1 -ojsonpath={.data.data} | base64 -d
#secretcontrolplane $ k -n one get secrets s1 -ojsonpath={.data.data} | base64 -d > /opt/ks/one
